name: Deploy with Client ID Injection
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Inject Client ID
        run: |
          sed -i "s|CLIENT_ID_PLACEHOLDER|${{ secrets.CLIENT_ID }}|g" auth.js
          echo "Client ID injected successfully"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
